# ------------------------------------------------------------------------------
#
#   Gitlab CI pipeline file
#
# ------------------------------------------------------------------------------

### Define the Packer+Ansible Docker image to usefor building

default:
  image: spride/packer-ansible:1.7.10

### Define build stages

stages:
  - validate
  - build

### Validate the Packer build script

validate-job:
  stage: validate
  script:
    - echo "Validating Packer file"
    - packer validate -syntax-only packer.pkr.hcl

### Initialize the Packer plugin and build the AMI

build-job:
  stage: build
  script:
    - echo "Initializing Packer environment"
    - packer init config.pkr.hcl
    - echo "Building AMI"
    - packer build -color=false -on-error=cleanup packer.pkr.hcl

